fc-rand-forest:
  input:
    - train: 'train.csv'
    - test: 'test.csv'
  output:
    - pred: 'pred.csv'
    - test: 'test.csv'
  format:
    - sep: ','
    - label_col: 'target'
  split:
    - mode: 'file'
    - dir: .
  n_estimators: 100
  max_depth: 5
  max_features: 'sqrt'
  max_samples: 0.5
  bootstrap: True
  mode: 'classification'
  random_state: 42
